### ISSUE TITLE
js-rpc: Migration to ESM

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/js-rpc#78]
This package should be possible to convert to ESM, all its dependencies are already ESM.

### Tasks

- [x] 1. Update all dependencies to ESM
- [x] 2. Migrate tests
- [x] 3. Migrate package.json
- [x] 4. Migrate src code

**Comment by CMCDragonkai** [comment]
Ok migrating to ESM will hit a problem with the way fastcheck is currently used.

See: https://github.com/dubzzz/fast-check/issues/4986#issuecomment-2285225681

It's when fastcheck is integrated with jest that's when there's a problem.

@amydevs had done something before to as a hack here.

It has something to do with:

* fastcheck
* jest
* swc

**Comment by CMCDragonkai** [comment]
To make this work, we have a few options:

1. not use the fast check jest integration, and just use fast check directly like we used to - a bit annoying, but not really that bad
2. Always monkey patch fast check jest integration to remove its import of `@jest/globals` as per @amydevs comment - this would only solve it in the case where fast check jest is doing this (its the only dependency where this is occurring)
3. Modify the transform chain as per https://github.com/swc-project/jest/issues/120#issuecomment-1770662124 somehow so that this prevents any problem with any new test dependency that might do that importing

The core of the problem is that jest mocking is not hoisted above ESM module imports, unlike CJS imports, and moving to ESM means that mocking won't really work.

**Comment by CMCDragonkai** [comment]
> To make this work, we have a few options:
> 
> 1. not use the fast check jest integration, and just use fast check directly like we used to - a bit annoying, but not really that bad
> 2. Always monkey patch fast check jest integration to remove its import of `@jest/globals` as per @amydevs comment - this would only solve it in the case where fast check jest is doing this (its the only dependency where this is occurring)
> 3. Modify the transform chain as per [Add hoisting of the "@jest/globals" import together with jest.mock swc-project/jest#120 (comment)](https://github.com/swc-project/jest/issues/120#issuecomment-1770662124) somehow so that this prevents any problem with any new test dependency that might do that importing
> 
> The core of the problem is that jest mocking is not hoisted above ESM module imports, unlike CJS imports, and moving to ESM means that mocking won't really work.

I think solution 1. could be achieved by writing our own fast check jest integration. It's a pretty simple package: https://github.com/dubzzz/fast-check/tree/main/packages/jest. It would be a simple utility package, rather than something large, so we wouldn't bother with even testing it.
